name: deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  deploy_frontend:
    if: ${{ contains(join(github.event.commits.*.message), '#deploy_frontend') && github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "meser"
          heroku_email: "1michaelohayon@gmail.com"
          appdir: "frontend"
  deploy_backend:
    if: ${{ contains(join(github.event.commits.*.message), '#deploy_backend') && github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nameless-shore-55160"
          heroku_email: "1michaelohayon@gmail.com"
          appdir: "backend"
