name: pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SECRET: ${{secrets.SECRET}}


jobs:
  backend_pipline:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip_backend') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: npm install
        run: npm install
        working-directory: ./backend

      - name: build
        run: npm run postinstall
        working-directory: ./backend

      - name: testing
        run: npm test
        working-directory: ./backend

  frontend_pipline:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip_frontend') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: npm install
        run: npm install
        working-directory: ./frontend

      - name: build
        run: npm run build
        working-directory: ./frontend


      - name: npm install backend for e2e tests
        run: npm install
        working-directory: ./backend

      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run start:all
          working-directory: ./frontend
          wait-on: http://localhost:4000


          
  tag_release:
    if: ${{ github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_BUMP: patch

